### ISSUE TITLE
[Bug]: Issue with RAG Implementation for Mistral Models in LibreChat

### ISSUE THREAD

**Issue by tarn-jihas** [danny-avila/LibreChat#3732] opened 2024-08-21 19:37 UTC
### What happened?

- Successfully added Mistral to LibreChat
- Attempted to set up Retrieval-Augmented Generation (RAG)
- Using OpenAI's embeddings for RAG

Issue:
Opening a new chat with any Mistral model (including Mistral Large Latest) and attaching a PDF results in an error.

Additional Information:
- The RAG feature works correctly with OpenAI models
- This issue appears to be specific to Mistral models

Questions:
1. Do other non-OpenAI models support RAG functionality in LibreChat?
2. If not, are there any known workarounds to implement RAG with Mistral models?

Any insights or suggestions would be greatly appreciated. Thank you!

### Steps to Reproduce

Added OpenAI and Mistral API keys to .env file
Added "RAG_API_URL=http://host.docker.internal:8000/" to .env
Added RAG_OPENAI_API_KEY to .env
Left EMBEDDINGS_PROVIDER and EMBEDDINGS_MODEL at default values
Copied librechat.yaml with Mistral entries
Started LibreChat locally using docker compose up

Steps to Reproduce:
7. Opened a new chat with a Mistral model
8. Attached a PDF file
9. After upload, entered a question or any text and sent the message
10. An error toast appeared at the top of the screen
11. The following error appeared in the logs:

### Relevant log output

```shell
LibreChat         | 2024-08-21 19:24:44 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat         | 2024-08-21 19:24:44 error: [handleAbortError] AI response error; aborting request: 422 status code (no body)
```

### Screenshots

![image](https://github.com/user-attachments/assets/e8871a86-3b3a-4185-a191-e69b97361b8a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-08-21 19:47
duplicate of underlying issue: https://github.com/danny-avila/LibreChat/issues/3048

**Closed by danny-avila** 2024-08-21 19:47 UTC
Labels: bug

**Comment by tarn-jihas** [comment] 2024-08-21 20:10
@danny-avila Hey Danny, thanks for the quick look. 

I've just checked the proposed fix here: https://github.com/danny-avila/LibreChat/issues/3048#issuecomment-2275917737

After running docker compose up --build 

I get the same error
```
error: [handleAbortError] AI response error; aborting request: 422 status code (no body)
```

So this one is perhaps not related to that.

**Comment by danny-avila** [comment] 2024-08-21 20:21
The proposed fix is not a one-size-fits-all solution, that's why it's not implemented. It's a deeper issue due to the strictness of the role order for those API providers.
