### ISSUE TITLE
Enhancement: Support numbered lists on desktop

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#4531] opened 2024-10-24 08:57 UTC
### What features would you like to see added?

The numbers that a model provides in a numbered list shall be shown to the user. They shall not be altered.

### More details

Instead of showing `1.`, `2.`, `3.`, `4.`, like the LLM provides (visible in raw message), LibreChat makes `1.`, `1.`, `1.`, `1.` out of them. 

The correct numbers should be displayed instead.

Chrome 130.0.6723.70 (Desktop), macOS 15.0.1, claude-3-5-sonnet-20241022, LibreChat v0.7.5-rc2

### Which components are impacted by your request?

UI

### Pictures

![Screenshot 2024-10-24 at 10 50 51](https://github.com/user-attachments/assets/bc1929eb-4a59-4612-8d18-04f0eccab20c)
![Screenshot 2024-10-24 at 10 50 41](https://github.com/user-attachments/assets/9c51d1f1-67d2-44d4-bccb-ae9780d8821e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thingersoft** [comment] 2024-10-24 23:50
This and #4120 share the same [root cause](https://github.com/danny-avila/LibreChat/issues/4120#issuecomment-2433984648).

In this case the html generated by react-markdown presents multiple `ol` elements each containing just one `li` rather than a single `ol` with multiple `li` elements.

To get the right numbers/markers react-markdown sets the `start` property on each `ol` (pretty hacky imho).
LibreChat overrides the default list item markers using the css `content` property and `counter` function on the `::marker` pseudo-element.
So the `start` property doesn't have any effect and each element starts with `1.`.

Note that the problem doesn't occur in Webkit browsers since `content` property for the `::marker` pseudo-element is ignored.

I'm about to submit a PR that solves both this and #4120 at the same time.

**Comment by danny-avila** [comment] 2024-11-23 00:21
Closed by #4120

**Closed** 2024-11-23 00:20 UTC
Labels: enhancement
