### ISSUE TITLE
Enhancement: Better handle large amounts of pasted input text

### ISSUE THREAD

**Issue by kzar** [danny-avila/LibreChat#2335] opened 2024-04-06 18:18 UTC
### What features would you like to see added?

One of the useful things about the Claude Opus model is the large context window, that can be used to do things like summarise large blocks of text. Unfortunately though, Librechat responds quite sluggishly when a large block of text is pasted into the input box.

### More details

The official Claude web UI handles this well, large amounts of text are displayed as a small "Pasted" icon instead and the app doesn't slow down. It would be nice if Librechat could do something similar.

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/155710/17144025-80c8-4cac-b09d-2583a3ecaf0b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-04-06 18:21
Thanks! I'll look into it

**Comment by danny-avila** [comment] 2024-04-06 21:06
> If it helps, I'm guessing they're [using the paste event](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event) and checking the clipboard length before deciding what to do.

Great point, will have to think how to best to implement

**Comment by danny-avila** [comment] 2024-04-16 14:01
Also FYI and mostly a note for myself. The "delay" for long text only happens on chrome and I narrowed down exactly why. There would need to be a compromise for the current optimizations being handled for the textarea to fix it, but also may not address for a while.

**Comment by kzar** [comment] 2024-04-16 16:12
If you want a second pair of eyes to look at that slow code, just shout (and link the code). Would be happy to have a quick look if it helps.

**Comment by jordantgh** [comment] 2024-04-17 07:03
Speaking personally, I am quite often editing the pasted text, so I'm not sure the claude approach is ideal in all cases. Arguably it's better practise to get everything just right before pasting, but often enough I change my mind about what to include in the context as I'm drafting my query.

**Comment by danny-avila** [comment] 2024-04-18 11:29
> If you want a second pair of eyes to look at that slow code, just shout (and link the code). Would be happy to have a quick look if it helps.

I figured out the root cause for this issue and I’ll be pushing a change today

**Comment by sbarrios93** [comment] 2024-05-14 16:16
Unfortunately, this is still happening (not sure if the changes were pushed @danny-avila )

**Comment by danny-avila** [comment] 2024-05-15 17:55
> Unfortunately, this is still happening (not sure if the changes were pushed @danny-avila )

can you describe what is still happening? On both firefox/chrome, pasting large amounts of text does not incur a noticeable delay

**Comment by danny-avila** [comment] 2024-05-16 18:15
Closing in favor of #2755  (same request) and the original inspiration for this issue, the slow loading of text via Chrome, is no longer an issue.

**Closed by danny-avila** 2024-05-16 18:15 UTC
Labels: enhancement
