### ISSUE TITLE
[Bug]: Unable to switch endpoints/models

### ISSUE THREAD

**Issue by cg-dot** [danny-avila/LibreChat#2334] opened 2024-04-06 12:48 UTC
### What happened?

After updating to the latest commit, I encountered a bug where I am unable to switch to any other endpoint/model when a default preset is pinned.

It seems to be caused by the changes introduced in commit f6a8488.

### Steps to Reproduce

1. Update to the latest commit(4767673)
2. Set a default preset
3. Try to switch to a different endpoint/model

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-04-06 13:46
Thanks I’ll take care of this today. That change was necessary but I figured I may not be homefree

**Comment by danny-avila** [comment] 2024-04-06 15:10
@cg-dot I'm actually not able to reproduce this on the latest commit, it's working as expected on chrome/firefox on the latest commit 🤔

**Comment by danny-avila** [comment] 2024-04-06 15:31
https://github.com/danny-avila/LibreChat/assets/110412045/277ca7aa-8195-4c5f-a55e-461d47de54a5

I made a screen recording, at following commit:

```bash
commit 476767355b80d85beefa911f316d28ab3247660f (HEAD -> main, origin/main, origin/HEAD)
```

Tried local npm and docker installations, both produce same results as the recording. I also have a remote instance that runs this image and can't reproduce it either: https://github.com/danny-avila/LibreChat/pkgs/container/librechat-dev-api

Going to keep trying with a couple different configurations (no config file, bare minimum variables, etc.)

**Comment by cg-dot** [comment] 2024-04-06 15:40
@danny-avila I've tried clearing browser's local storage and cookies, but I can still reproduce the issue 100% on my end. However, when I reverted commit f6a8488, everything started working normally again.

I couldn't find any errors in the logs or the browser console. From what I can see in the "Network" tab, it seems that when I try to switch to another endpoint, it immediately switches back to the endpoint of the Default pinned preset.

![](https://github.com/danny-avila/LibreChat/assets/22318727/411ce8fb-79b8-4184-814a-297bcfc0471d)

**Comment by danny-avila** [comment] 2024-04-06 15:44
> @danny-avila I've tried clearing browser's local storage and cookies, but I can still reproduce the issue 100% on my end. However, when I reverted commit [f6a8488](https://github.com/danny-avila/LibreChat/commit/f6a84887e1906750d865f3dfb5cde1335eaf3e57), everything started working normally again.
> 
> I couldn't find any errors in the logs or the browser console. From what I can see in the "Network" tab, it seems that when I try to switch to another endpoint, it immediately switches back to the endpoint of the default preset.
> 
> ![](https://private-user-images.githubusercontent.com/22318727/320216359-411ce8fb-79b8-4184-814a-297bcfc0471d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTg0MDgsIm5iZiI6MTcxMjQxODEwOCwicGF0aCI6Ii8yMjMxODcyNy8zMjAyMTYzNTktNDExY2U4ZmItNzliOC00MTg0LTgxNGEtMjk3YmNmYzA0NzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDE1NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MDVkYzhkNDk0ZjkwMmY1YWE4YWFjODM5ZDI5N2I4MDllZGYwZWM1ZWI5Y2QwMTg4OWU3YzA4MGM3MzUxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0M065sLKLaOi4DQVAjVfxzYeYPzrC59fPmvwJKtxJs)

Thanks maybe it's a browser rendering issue on different PCs. I can try it on my phone

**Comment by KiGamji** [comment] 2024-04-06 15:47
> I couldn't find any errors in the logs or the browser console. From what I can see in the "Network" tab, it seems that when I try to switch to another endpoint, it immediately switches back to the endpoint of the default preset.
Same here. And it actually uses the preset endpoint instead of the selected one, so that's not just a visual bug,
@danny-avila

**Comment by danny-avila** [comment] 2024-04-06 15:48
Can you try these instructions and see if it generates any different behavior (if using docker)?

https://docs.librechat.ai/install/installation/docker_compose_install.html#updating-librechat

```bash
# Stop the running container(s)
docker compose down

# Pull latest project changes
git pull

# Pull the latest LibreChat image (default setup)
docker compose pull

# If building the LibreChat image Locally, build without cache (legacy setup)
# docker compose build --no-cache

# Start LibreChat
docker compose up
```

**Comment by KiGamji** [comment] 2024-04-06 15:51
> Can you try these instructions and see if it generates any different behavior (if using docker)?
> 
> https://docs.librechat.ai/install/installation/docker_compose_install.html#updating-librechat
> 
> ```shell
> # Stop the running container(s)
> docker compose down
> 
> # Pull latest project changes
> git pull
> 
> # Pull the latest LibreChat image (default setup)
> docker compose pull
> 
> # If building the LibreChat image Locally, build without cache (legacy setup)
> # docker compose build --no-cache
> 
> # Start LibreChat
> docker compose up
> ```

Didn't work. I am already using the latest image. And yeah, I am using docker.

**Comment by cg-dot** [comment] 2024-04-06 15:54
> Can you try these instructions and see if it generates any different behavior (if using docker)?
That's pretty much how I installed it. (except the vectordb and rag_api containers since I don't need them)

**Comment by KiGamji** [comment] 2024-04-06 15:55
oh yeah, the only thing is that I don't use RAG API as well. Maybe that will help

**Comment by cjccjj** [comment] 2024-04-06 15:58
I deployed on Railway and having the same issue. It happens on Chrome on Windows PC and also Firefox on a Macbook. Already logout and login, restarting browsers and cleaning browser data.

**Comment by danny-avila** [comment] 2024-04-06 16:01
I’m trying my best to reproduce it. Once I can, I’ll get to the bottom of it. Worse comes to worse I’ll revert the outlier commit

**Comment by danny-avila** [comment] 2024-04-06 20:10
merged a potential fix, however i could not reproduce on several different browsers/computers, cache reset and not. I just went ahead and edited things that stood out that could be a potential cause

**Comment by cg-dot** [comment] 2024-04-06 20:32
> merged a potential fix, however i could not reproduce on several different browsers/computers, cache reset and not. I just went ahead and edited things that stood out that could be a potential cause

@danny-avila I can no longer reproduce the issue on my end after updating to the latest commit. Thanks for the quick fix!

**Comment by danny-avila** [comment] 2024-04-06 21:04
> > merged a potential fix, however i could not reproduce on several different browsers/computers, cache reset and not. I just went ahead and edited things that stood out that could be a potential cause
> 
> @danny-avila I can no longer reproduce the issue on my end after updating to the latest commit. Thanks for the quick fix!

Awesome @fuegovic reported the same who was also experiencing, happy to close this issue!

**Closed by danny-avila** 2024-04-06 21:04 UTC
Labels: bug
