### ISSUE TITLE
chat-mongodb, permission denied for mkdir /data/db/journal

### ISSUE THREAD

**Issue by phdye** [danny-avila/LibreChat#3645] opened 2024-08-15 00:11 UTC
### What happened?

Just trying to bringing it up for the first time.

### Steps to Reproduce

docker-compose up

### Relevant log output

```shell
chat-mongodb      | {"t":{"$date":"2024-08-15T00:00:14.069+00:00"},"s":"E",  "c":"STORAGE",  "id":22312,   "ctx"\
:"initandlisten","msg":"Error creating journal directory","attr":{"directory":"/data/db/journal","error":"boost:\
:filesystem::create_directory: Permission denied [system:13]: \"/data/db/journal\""}}
chat-mongodb      | {"t":{"$date":"2024-08-15T00:00:14.070+00:00"},"s":"E",  "c":"CONTROL",  "id":20558,   "ctx"\
:"initandlisten","msg":"std::exception in initAndListen, terminating","attr":{"error":"boost::filesystem::create\
_directory: Permission denied [system:13]: \"/data/db/journal\""}}
chat-mongodb      | {"t":{"$date":"2024-08-15T00:00:14.070+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx"\
:"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":15000}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-08-15 01:33
This is a permission issue in your environment, and is a duplicate of the other issue you opened.

**Closed by danny-avila** 2024-08-15 01:33 UTC
