### ISSUE TITLE
[Bug]: OpenId authenticator overwrites user-provided avatar upon login

### ISSUE THREAD

**Issue by cmurtaugh** [danny-avila/LibreChat#2982] opened 2024-06-06 21:23 UTC
### What happened?

With LibreChat configured to use OpenID authentication with an IdP that does not provide a `picture` attribute, logging into the application will remove an existing manually-uploaded avatar. 

Ideally the authenticator would only overwrite the existing `user.avatar` value if that value doesn't contain the string "manual=true" (which is present when the avatar was explicitly provided by the user). 

### Steps to Reproduce

1. Log into LibreChat and upload a new user avatar image. Note correct avatar display.
2. Log out and log back in again.
3. Avatar image is missing.

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-06-06 21:26
duplicate of https://github.com/danny-avila/LibreChat/issues/2056

**Closed by danny-avila** 2024-06-06 21:26 UTC
Labels: bug
