### ISSUE TITLE
[Bug]:  agentOptions.model  only is gpt-4o-2024-05-13 and plugin error when  no plugin is selected!

### ISSUE THREAD

**Issue by ptozys2** [danny-avila/LibreChat#3872] opened 2024-09-01 10:51 UTC
### What happened?

Bug 1: When using the plugins feature, I noticed that no matter which model type I select, the value of agentOptions.model is always gpt-4o-2024-05-13.

Bug 2: When using the plugins feature, if no plugin is selected and a conversation is initiated, the backend throws an error, and the program exits.
Error message: "error: There was an uncaught error: Cannot read properties of undefined (reading 'map')"

### Steps to Reproduce

Bug 1: When using the plugins feature, I noticed that no matter which model type I select, the value of agentOptions.model is always gpt-4o-2024-05-13.

Bug 2: When using the plugins feature, if no plugin is selected and a conversation is initiated, the backend throws an error, and the program exits.
Error message: "error: There was an uncaught error: Cannot read properties of undefined (reading 'map')"

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-09-01 12:35
1. I can't reproduce this
2. fixed in the linked PR

**Closed** 2024-09-01 12:35 UTC
Labels: bug

**Comment by ptozys2** [comment] 2024-09-01 12:59
very nice, thanks your job, it can work!

**Comment by ptozys2** [comment] 2024-09-01 13:13
bug 1 reproduce :
Clear the browser cache and restart the backend service.

![1725196039646](https://github.com/user-attachments/assets/effb31eb-eea0-486e-b779-6bae51f27894)

file : client/src/hooks/Chat/useChatFunctions.ts
func:  const ask: TAskFunction 
.
.

    const submission: TSubmission = {
      conversation: {
        ...conversation,
        conversationId,
      },
      endpointOption,
      userMessage: {
        ...currentMsg,
        generation,
        responseMessageId,
        overrideParentMessageId: isRegenerate ? messageId : null,
      },
      messages: currentMessages,
      isEdited: isEditOrContinue,
      isContinued,
      isRegenerate,
      initialResponse,
    };
    **console.log('ask: Prepared submission object:', submission);** => output :model: 'gpt-4o-2024-05-13',
