### ISSUE TITLE
[Bug]: Issue with ModelSpecs

### ISSUE THREAD

**Issue by swiftdev29** [danny-avila/LibreChat#4975] opened 2024-12-13 17:22 UTC
### What happened?

Pretty simple actually, My model spec config is pasted below. When creating a new chat, or starting Librechat afresh, the modelspec name in the chat box is displayed correctly. However on going to an old chat, the chatbox name changes to the model name that the modelspec is using. (Example : GPT-4o)

```modelSpecs:
    enforce: true
    prioritize: true
    list:
      - name: "Max"
        label: "Max"
        description: "Smartest model"
        iconURL: "url"
        preset:
          default: true
          endpoint: "mycustomendpoint"
          model: "chatgpt-4o-latest"
          temperature: 0.90
          modelLabel: "Max"
          greeting: |
            Hello! How can I help you today?
          promptPrefix: |
           You are a friendly assistant.
```     

### Steps to Reproduce

1. Create a Model Spec with an OpenAI model.
2. Set enforce and prioritize true
3. create a chat on LC and then close the application/website.
4 Restart again, and go to that chat. The chatbox model displays the actual model name. (Like GPT-4o)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile (iOS), Mobile (Android)

### Screenshots

![IMG_0666](https://github.com/user-attachments/assets/30a6f7f6-fbdc-488b-b94a-f0cf904ed5f4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-12-13 20:40
Thanks, this is a duplicate of #4749

**Closed** 2024-12-13 20:40 UTC
Labels: bug

**Comment by danny-avila** [comment] 2024-12-14 16:25
> > Thanks, this is a duplicate of #4749
> 
> Oh okay. You said it was resolved in that issue though, the chatbox input placeholder name still doesnt change and shows the original model name. If I change the model spec to something LibreChat doesnt support by default (like llama-3.2-90b-vision-preview), then it shows the name of the custom endpoint in which it is in. (According to the config i pasted above it shows MyCustomEndpoint).

I see the issue now, it's a simple fix, will push it up soon. Thanks for the report!
