### ISSUE TITLE
[Bug]: Conversation isn't getting imported

### ISSUE THREAD

**Issue by egcash** [danny-avila/LibreChat#2800] opened 2024-05-20 13:33 UTC
### What happened?

I exported my conversation and downloaded from another Librechat instance, 
I tried to import it on another Librechat, I'm getting this error message, "Unsupported Import type."

### Steps to Reproduce

1. Exported conversation in json format from another Librechat instance
2. Imported on another Librechat that's having the issue
3. I'm sure that both of the Librechat instance is latest.
4. My file is in json format

### What browsers are you seeing the problem on?

Mobile (Android)

### Relevant log output

```shell
Unsupported import type
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egcash** [comment] 2024-05-20 13:34
> ### What happened?
> I exported my conversation and downloaded from another Librechat instance, I tried to import it on another Librechat, I'm getting this error message, "Unsupported Import type."
> 
> ### Steps to Reproduce
> 1. Exported conversation in json format from another Librechat instance
> 2. Imported on another Librechat that's having the issue
> 3. I'm sure that both of the Librechat instance is latest.
> 4. My file is in json format
> 
> ### What browsers are you seeing the problem on?
> Mobile (Android)
> 
> ### Relevant log output
> ```shell
> Unsupported import type
> ```
> 
> ### Screenshots
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Error from console: 
error: user: 65675e2494b7143cfxxxxxx | Failed to import conversation:  Unsupported import type

**Comment by danny-avila** [comment] 2024-05-20 13:35
Can you share the JSON file? This might be a duplicate of https://github.com/danny-avila/LibreChat/issues/2794

**Comment by danny-avila** [comment] 2024-05-20 14:12
Ok thanks! Will look into it

**Closed** 2024-05-29 13:15 UTC
Labels: bug
