### ISSUE TITLE
maximumFileSizeToCacheInBytes (client/vite.config.ts) may need increasing 

### ISSUE THREAD

**Issue by lochiiconnectivity** [danny-avila/LibreChat#3857] opened 2024-08-30 08:08 UTC
### What happened?

build warning 

```
warnings
  assets/vendor.8_Lw4OZu.js is 3.27 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
```

This is currently set to 3MB in `client/vite.config.ts` , so may need increasing .

The asset at `assets/vendor.8_Lw4OZu.js ` in my case appears to be part of react.

 

### Steps to Reproduce

1. npm run build
2. experience warning

### Relevant log output

```shell
warnings
  assets/vendor.8_Lw4OZu.js is 3.27 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment] 2024-08-30 10:29
Not a bug, before release I will add more manual chunks to lower the size of this.

**Comment by danny-avila** [comment] 2024-10-19 12:44
recent changes to vite-PWA require the ppre-cache size to be increased, regardless of manual chunking, so I'm closing this issue.

**Closed by danny-avila** 2024-10-19 12:44 UTC
